create table bot_user (id int8 generated by default as identity, user_id int8, primary key (id));
create table list (id int8 generated by default as identity, name varchar(255), user_id int8, primary key (id));
create table list_item (id int8 generated by default as identity, checked boolean not null, content varchar(255), list_id int8, primary key (id));
alter table if exists bot_user add constraint user_id_idx unique (user_id);
alter table if exists list add constraint FKfbbmf91tx34hhpr4t8ivseohp foreign key (user_id) references bot_user on delete cascade;
alter table if exists list_item add constraint FK1ddq3ct1ulogjn5ijs8ert7hw foreign key (list_id) references list on delete cascade;